//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWithDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClothWarehouse
    {
        public string rollCode { get; set; }
        public string clothCode { get; set; }
        public int rollWidth { get; set; }
        public int rollLength { get; set; }
    
        public virtual Cloth Cloth { get; set; }
    }
}
