//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWithDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Furniture()
        {
            this.FurnitureWarehouses = new HashSet<FurnitureWarehouse>();
            this.ProductFurnitures = new HashSet<ProductFurniture>();
        }
    
        public string furCode { get; set; }
        public string furName { get; set; }
        public string furType { get; set; }
        public decimal furWidth { get; set; }
        public Nullable<decimal> furLength { get; set; }
        public Nullable<decimal> furWeight { get; set; }
        public string furPicture { get; set; }
        public decimal furPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FurnitureWarehouse> FurnitureWarehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductFurniture> ProductFurnitures { get; set; }
    }
}
