//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWithDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FurnitureWarehouse
    {
        public string batch { get; set; }
        public string furCode { get; set; }
        public int bathQty { get; set; }
    
        public virtual Furniture Furniture { get; set; }
    }
}
