//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWithDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderedProduct
    {
        public int ordCode { get; set; }
        public string productCode { get; set; }
        public int ProductQty { get; set; }
    
        public virtual Ord Ord { get; set; }
        public virtual Product Product { get; set; }
    }
}
