//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWithDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFurniture
    {
        public string furCode { get; set; }
        public string productCode { get; set; }
        public string placement { get; set; }
        public Nullable<int> prodFurWidth { get; set; }
        public Nullable<int> prodFurLength { get; set; }
        public Nullable<int> prodFurRotation { get; set; }
        public int prodFurQty { get; set; }
    
        public virtual Furniture Furniture { get; set; }
        public virtual Product Product { get; set; }
    }
}
